fiber:
  secret_key: "snjshicdnsjkdbshassbsdbcndskjfdbdsvywgdichugwe8ee2"
  host: "127.0.0.1"
  port: 8001

postgres:
  host: "localhost"
  port: 5433
  user: "postgres"
  password: "ruslangv"
  dbname: "xaxaton"
