fiber:
  secret_key: "snjshicdnsjkdbshassbsdbcndskjfdbdsvywgdichugwe8ee2"
  host: "127.0.0.1"
  port: 8001

postgres:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "ruslangv"
  dbname: "xaxaton_postgres"
