version: '3.8'

networks:
  network:

services:
  xaxaton_server:
    image: gipnotyin/xaxaton:latest
    restart: always
    ports:
      - "127.0.0.1:8001:8001"
    depends_on:
      - postgres
    volumes:
      - server-data:/var/lib/server/data
      - ./config_prod.yaml:/config.yaml
    networks:
      - network

  postgres:
    image: postgres:latest
    container_name: xaxaton_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env.postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - network

volumes:
  postgres-data:
  server-data: